# Generated by Django 3.1.12 on 2023-03-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230304_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
